from enum import Enum

#define L4_DEVICE_IDS
class L4_DEVICE_IDS(Enum):
    DEVICE_board						    = 0x00  # Board as a whole  - singleton 
    DEVICE_events						    = 0x01  # Event Broker  - singleton 
    DEVICE_motor						    = 0x02  # Motor, one and only per board 
    DEVICE_lld							    = 0x03  # LLD device */ 
    DEVICE_slt_sensor_1_in				    = 0x10  # Slot sensor 1 
    DEVICE_slt_sensor_2_in				    = 0x11  # Slot sensor 2 
    DEVICE_slt_sensor_3_in				    = 0x12  # Slot sensor 3 
    DEVICE_sw_1_in						    = 0x13  # DIP switch, pos 0 
    DEVICE_sw_2_in						    = 0x14  # DIP switch, pos 1 
    DEVICE_sw_3_in						    = 0x15  # DIP switch, pos 2 
    DEVICE_sw_4_in						    = 0x16  # DIP switch, pos 3 
    DEVICE_id_1_in						    = 0x17  # Board ID, pos 0 
    DEVICE_id_2_in						    = 0x18  # Board ID, pos 1 
    DEVICE_id_3_in						    = 0x19  # Board ID, pos 2 
    DEVICE_alert_rx_in					    = 0x1A  # Alert line, RX input 
    DEVICE_smc_stall_l_in				    = 0x1B  # drv8711 STALLn signal 
    DEVICE_smc_fault_l_in				    = 0x1C  # drv8711 FAULTn signal 
    DEVICE_smc_int_in					    = 0x1D  # drv8711 VINT signal 
    DEVICE_qec_pa_in					    = 0x1E  # Quadrature decoder, phase A input 
    DEVICE_qec_pb_in					    = 0x1F  # Quadrature decoder, phase B input 
    DEVICE_rs485_rx_in					    = 0x20  # RS485 port, RX input 
    DEVICE_sol_efuse_flt_l_in			    = 0x21  # Solenoid fuse input 
    DEVICE_sol_sense_in				        = 0x22  # Solenoid sensor 
    DEVICE_sleeve_temp_flt_l_in		        = 0x23  #
    DEVICE_sleeve_efuse_flt_l_in		    = 0x24  #
    DEVICE_sleeve_heat_en_out			    = 0x25  #
    DEVICE_upper_sleeve_heat_pwm_l_pwm	    = 0x26  #
    DEVICE_lower_sleeve_heat_pwm_l_pwm	    = 0x27  #
    DEVICE_piercer_flag_in				    = 0x30  # Piercer Flag ID 
    DEVICE_foot_flag_in				        = 0x31  # Foot Flag ID 
    DEVICE_cap_flag_in					    = 0x32  # Cap Flag ID 
    DEVICE_probe_flag_in				    = 0x33  # Probe Flag ID 
    DEVICE_probe_temp_flt_l_in			    = 0x34  #
    DEVICE_probe_efuse_flt_l_in		        = 0x35  #
    DEVICE_probe_heat_en_out			    = 0x36  #
    DEVICE_upper_probe_heat_pwm_l_pwm	    = 0x37  #
    DEVICE_lower_probe_heat_pwm_l_pwm	    = 0x38  #
    DEVICE_smc_scs_out					    = 0x40  # 
    DEVICE_smc_clk_out					    = 0x41  # drv8711 SPI clock 
    DEVICE_rs485_tx_out				        = 0x42  # RS485 port, TX output 
    DEVICE_sol_drv_l_pwm				    = 0x43  # Solenoid control output 
    DEVICE_sda_out						    = 0x44  # SDA of I2C port to EEPROM 
    DEVICE_scl_out						    = 0x45  # SCL of I2C port to EEPROM 
    DEVICE_smc_step_out				        = 0x46  # drv8711 STEP signal 
    DEVICE_smc_mosi_out				        = 0x47  # drv8711 SPI MOSI 
    DEVICE_smc_miso_out				        = 0x48  # drv8711 SPI MISO
    DEVICE_alert_tx_out				        = 0x49  # Alert line, TX output 
    DEVICE_rs485_txe_out				    = 0x4A  # RS485 transmit enable output
    DEVICE_led1_out					        = 0x4B  # LED for developer's use
    DEVICE_led2_out					        = 0x4C  #
    DEVICE_slt_sensor_en_out			    = 0x4D  # Slot sensor enable output
    DEVICE_smc_sleep_l_out				    = 0x4E  # drv8711 SLEEPn signal 
    DEVICE_smc_reset_out				    = 0x4F  # drv8711 RESET signal 
    DEVICE_smc_dir_out					    = 0x50  # drv8711 DIR signal
    DEVICE_smc_bin1_out				        = 0x51  # drv8711 BIN1 signal
    DEVICE_smc_bin2_out				        = 0x52  # drv8711 BIN2 signal
    DEVICE_sol_en_out					    = 0x53  # Solenoid Enable output 
    DEVICE_ee_wp_out					    = 0x54  # 
    DEVICE_fan_en_l_out				        = 0x55  #
    DEVICE_fan1_pwm_pwm				        = 0x56  #
    DEVICE_fan2_pwm_pwm				        = 0x57  #
    DEVICE_eot_sensor_b_in				    = 0x61  #
    DEVICE_cap_sensor_b_in				    = 0x62  #
    DEVICE_spare_12_out				        = 0x63  #
    DEVICE_spare_13_out				        = 0x64  #
    DEVICE_solenoid_efuse_flt_l_in		    = 0x71  #
    DEVICE_solenoid_en_out				    = 0x72  #
    DEVICE_solenoid_drive_l_pwm		        = 0x73  #
    DEVICE_solenoid_sense_in			    = 0x74  #

#define L4_BOARD_COMMANDS
class L4_COMMAND_CODES(Enum):
    COMMAND_getver			= 0x01 	#  get L4 firmware version */)
    COMMAND_getcmdver		= 0x02 	#  get version of command set */)
    COMMAND_status_get		= 0x00 	#  no action on L4 */) 
    COMMAND_ack_completion	= 0xF0 	#  acknowledge command completion */) 
    COMMAND_data_plus		= 0xF1 	#  request streaming data */)
    COMMAND_startdef		= 0x10     #  start event definition session */) 
    COMMAND_enddef			= 0x11 	#  end event definition session */) 
    COMMAND_idxinc			= 0x17 	#  increment event index 
    COMMAND_genevt			= 0x12 	#  tell event source what event to generate */) 
    COMMAND_genflt			= 0x13 	#  tell event source when to generate fault */) 
    COMMAND_clrflt			= 0x14 	#  clear defined faults */) 
    COMMAND_hndlevt		    = 0x15 	#  tell event handler what event to handle */) 
    COMMAND_enable			= 0x20 	#  enable/disable motor */)
    COMMAND_movabs			= 0x21 	#  move absolute (profile, position), return (motpos, encpos) */) 
    COMMAND_movrel			= 0x22 	#  move relative (profile, position), return (motpos, encpos) */) 
    COMMAND_change			= 0x23 	#  change speed using profile */) 
    COMMAND_stop			= 0x24     #  stop using profile (0=current) */) 
    COMMAND_abort			= 0x25 	#  abort */) 
    COMMAND_setpos			= 0x26 	#  set position */) 
    COMMAND_getpos			= 0x27 	#  get position, return (motpos, encpos, encraw) */) 
    COMMAND_setrpw			= 0x28 	#  set run power % */) 
    COMMAND_getrpw			= 0x29 	#  get run power % */) 
    COMMAND_sethpw			= 0x2A 	#  set hold power % */) 
    COMMAND_gethpw			= 0x2B 	#  get hold power % */) 
    COMMAND_setreg			= 0x2C 	#  set register value ?*/) 
    COMMAND_getreg			= 0x2D 	#  get register value ?*/) 
    COMMAND_encmon			= 0x2E 	#  enable/disable encoder monitor (10kHz sampling divider) */) 
    COMMAND_setdump		    = 0x2F 	#  dump */) 
    COMMAND_setprof		    = 0x30 	#  set profile parameter (???) */) 
    COMMAND_getprof		    = 0x31 	#  get profile parameter (???) */) 
    COMMAND_sclprof		    = 0x32 	#  scale profile by specified factor */) 
    COMMAND_evtrec			= 0x33 	#  get position at specified event */) 
    COMMAND_sethdel		    = 0x34 	#  set hold delay in ticks */) 
    COMMAND_gethdel		    = 0x35 	#  get hold delay */) 
    COMMAND_setidel		    = 0x36 	#  set idle delay in ticks */) 
    COMMAND_getidel		    = 0x37 	#  get idle delay */) 
    COMMAND_settlr			= 0x38 	#  set step loss tolerance */) 
    COMMAND_gettlr			= 0x39 	#  get step loss tolerance */) 
    COMMAND_movinf			= 0x3A 	#  move indefinitely (profile, direction (+1/-1)), return (motpos, encpos) */) 
    COMMAND_movevt			= 0x3B 	#  start move on event (event index), return (motpos, encpos) */) 
    COMMAND_setscaling		= 0x3C 	#  set full steps per revolution scale of the motor and and encoder lines per rev */) 
    COMMAND_getscaling		= 0x3D 	#  get full steps per revolution scale of the motor and encoder lines per rev */) 
    COMMAND_read			= 0x50 	#  --
    COMMAND_setbit			= 0x58 	#  set bit value */)
    COMMAND_getbit			= 0x59 	#  get back set bit value */)
    COMMAND_readbit         = 0x5A 	#  read actual pin state of bit output */)
    COMMAND_sqwave			= 0x5B 	#  generate square wave up to 5kHz */)
    COMMAND_hfwave			= 0x5C 	#  generate square wave > 5kHz*/)
    COMMAND_testmode1		= 0x5D 	#  switch to test mode 1 */)
    COMMAND_testmode2		= 0x5E 	#  switch to test mode 2 */) 
    COMMAND_setpwm			= 0x60 	#  --
    COMMAND_getpwm			= 0x61 	#  --
    COMMAND_setpol			= 0x62 	#  --
    COMMAND_pwmen			= 0x63 	#  --
    COMMAND_readadc		    = 0x70 	#  return a single reading */) 
    COMMAND_streamadc		= 0x71 	#  start/stop streaming data */) 
    COMMAND_adcdata		    = 0x72 	#  command code for streamed data */)

# Define L4 Board Response Status Codes
class L4_STATUS_CODES(Enum):
	STATUS_Success = 0x0 #Success */ \
	STATUS_CommandExecuting = 0x01 #Command is pending completion */ \
	STATUS_CommandAborted = 0x02 #Command was aborted */ \
	STATUS_ErrorInvalidDevice = 0x81 #Invalid device ID in the command */ \
	STATUS_ErrorInvalidCommand = 0x82 #Invalid command */ \
	STATUS_ErrorInvalidArgCount = 0x83 #Invalid number of command arguments */ \
	STATUS_ErrorInvalidArgument = 0x84 #Invalid command argument */ \
	STATUS_ErrorDeviceBusy = 0x85 #Command can't be executed, device is busy */ \
	STATUS_ErrorMotorStepLoss = 0x86 #Step loss detected */ \
	STATUS_ErrorEStop = 0x87 #E-Stop condition is detected */ \
	STATUS_ErrorNotSupported = 0x88 #Function not supported */ \
	STATUS_ErrorResourceNotAvailable = 0x89 #Out of specified resource */ \